[package]
name = "file-uploader"
version = "1.0.0"
description = "Class to facilitate storage of large files"
repository = "https://github.com/ArielRobotti/file-uploader.git"
keywords = [ "file", "assets", "uploader" ]
license = "MIT"

[dependencies]
map = "9.0.1"